// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: serverPostFunc.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverPostFunc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_serverPostFunc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_serverPostFunc_proto_rawDescGZIP(), []int{0}
}

type PostURLIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputURL string `protobuf:"bytes,1,opt,name=InputURL,proto3" json:"InputURL,omitempty"`
}

func (x *PostURLIn) Reset() {
	*x = PostURLIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverPostFunc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostURLIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostURLIn) ProtoMessage() {}

func (x *PostURLIn) ProtoReflect() protoreflect.Message {
	mi := &file_serverPostFunc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostURLIn.ProtoReflect.Descriptor instead.
func (*PostURLIn) Descriptor() ([]byte, []int) {
	return file_serverPostFunc_proto_rawDescGZIP(), []int{1}
}

func (x *PostURLIn) GetInputURL() string {
	if x != nil {
		return x.InputURL
	}
	return ""
}

type PostURLOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultURL string `protobuf:"bytes,1,opt,name=ResultURL,proto3" json:"ResultURL,omitempty"`
}

func (x *PostURLOut) Reset() {
	*x = PostURLOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverPostFunc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostURLOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostURLOut) ProtoMessage() {}

func (x *PostURLOut) ProtoReflect() protoreflect.Message {
	mi := &file_serverPostFunc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostURLOut.ProtoReflect.Descriptor instead.
func (*PostURLOut) Descriptor() ([]byte, []int) {
	return file_serverPostFunc_proto_rawDescGZIP(), []int{2}
}

func (x *PostURLOut) GetResultURL() string {
	if x != nil {
		return x.ResultURL
	}
	return ""
}

type GetURLIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputURL string `protobuf:"bytes,1,opt,name=InputURL,proto3" json:"InputURL,omitempty"`
}

func (x *GetURLIn) Reset() {
	*x = GetURLIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverPostFunc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLIn) ProtoMessage() {}

func (x *GetURLIn) ProtoReflect() protoreflect.Message {
	mi := &file_serverPostFunc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLIn.ProtoReflect.Descriptor instead.
func (*GetURLIn) Descriptor() ([]byte, []int) {
	return file_serverPostFunc_proto_rawDescGZIP(), []int{3}
}

func (x *GetURLIn) GetInputURL() string {
	if x != nil {
		return x.InputURL
	}
	return ""
}

type GetURLOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultURL string `protobuf:"bytes,1,opt,name=ResultURL,proto3" json:"ResultURL,omitempty"`
}

func (x *GetURLOut) Reset() {
	*x = GetURLOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverPostFunc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLOut) ProtoMessage() {}

func (x *GetURLOut) ProtoReflect() protoreflect.Message {
	mi := &file_serverPostFunc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLOut.ProtoReflect.Descriptor instead.
func (*GetURLOut) Descriptor() ([]byte, []int) {
	return file_serverPostFunc_proto_rawDescGZIP(), []int{4}
}

func (x *GetURLOut) GetResultURL() string {
	if x != nil {
		return x.ResultURL
	}
	return ""
}

type BatchShortenInElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationID string `protobuf:"bytes,1,opt,name=CorrelationID,proto3" json:"CorrelationID,omitempty"`
	InputURL      string `protobuf:"bytes,2,opt,name=InputURL,proto3" json:"InputURL,omitempty"`
}

func (x *BatchShortenInElement) Reset() {
	*x = BatchShortenInElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverPostFunc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchShortenInElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenInElement) ProtoMessage() {}

func (x *BatchShortenInElement) ProtoReflect() protoreflect.Message {
	mi := &file_serverPostFunc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenInElement.ProtoReflect.Descriptor instead.
func (*BatchShortenInElement) Descriptor() ([]byte, []int) {
	return file_serverPostFunc_proto_rawDescGZIP(), []int{5}
}

func (x *BatchShortenInElement) GetCorrelationID() string {
	if x != nil {
		return x.CorrelationID
	}
	return ""
}

func (x *BatchShortenInElement) GetInputURL() string {
	if x != nil {
		return x.InputURL
	}
	return ""
}

type BatchShortenIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*BatchShortenInElement `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *BatchShortenIn) Reset() {
	*x = BatchShortenIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverPostFunc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchShortenIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenIn) ProtoMessage() {}

func (x *BatchShortenIn) ProtoReflect() protoreflect.Message {
	mi := &file_serverPostFunc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenIn.ProtoReflect.Descriptor instead.
func (*BatchShortenIn) Descriptor() ([]byte, []int) {
	return file_serverPostFunc_proto_rawDescGZIP(), []int{6}
}

func (x *BatchShortenIn) GetData() []*BatchShortenInElement {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchShortenOutElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationID string `protobuf:"bytes,1,opt,name=CorrelationID,proto3" json:"CorrelationID,omitempty"`
	ResultURL     string `protobuf:"bytes,2,opt,name=ResultURL,proto3" json:"ResultURL,omitempty"`
}

func (x *BatchShortenOutElement) Reset() {
	*x = BatchShortenOutElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverPostFunc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchShortenOutElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenOutElement) ProtoMessage() {}

func (x *BatchShortenOutElement) ProtoReflect() protoreflect.Message {
	mi := &file_serverPostFunc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenOutElement.ProtoReflect.Descriptor instead.
func (*BatchShortenOutElement) Descriptor() ([]byte, []int) {
	return file_serverPostFunc_proto_rawDescGZIP(), []int{7}
}

func (x *BatchShortenOutElement) GetCorrelationID() string {
	if x != nil {
		return x.CorrelationID
	}
	return ""
}

func (x *BatchShortenOutElement) GetResultURL() string {
	if x != nil {
		return x.ResultURL
	}
	return ""
}

type BatchShortenOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*BatchShortenOutElement `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *BatchShortenOut) Reset() {
	*x = BatchShortenOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverPostFunc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchShortenOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenOut) ProtoMessage() {}

func (x *BatchShortenOut) ProtoReflect() protoreflect.Message {
	mi := &file_serverPostFunc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenOut.ProtoReflect.Descriptor instead.
func (*BatchShortenOut) Descriptor() ([]byte, []int) {
	return file_serverPostFunc_proto_rawDescGZIP(), []int{8}
}

func (x *BatchShortenOut) GetData() []*BatchShortenOutElement {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteURLIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputURLs []string `protobuf:"bytes,1,rep,name=InputURLs,proto3" json:"InputURLs,omitempty"`
}

func (x *DeleteURLIn) Reset() {
	*x = DeleteURLIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverPostFunc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteURLIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLIn) ProtoMessage() {}

func (x *DeleteURLIn) ProtoReflect() protoreflect.Message {
	mi := &file_serverPostFunc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLIn.ProtoReflect.Descriptor instead.
func (*DeleteURLIn) Descriptor() ([]byte, []int) {
	return file_serverPostFunc_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteURLIn) GetInputURLs() []string {
	if x != nil {
		return x.InputURLs
	}
	return nil
}

type URLPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortURL    string `protobuf:"bytes,1,opt,name=ShortURL,proto3" json:"ShortURL,omitempty"`
	OriginalURL string `protobuf:"bytes,2,opt,name=OriginalURL,proto3" json:"OriginalURL,omitempty"`
}

func (x *URLPair) Reset() {
	*x = URLPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverPostFunc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLPair) ProtoMessage() {}

func (x *URLPair) ProtoReflect() protoreflect.Message {
	mi := &file_serverPostFunc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLPair.ProtoReflect.Descriptor instead.
func (*URLPair) Descriptor() ([]byte, []int) {
	return file_serverPostFunc_proto_rawDescGZIP(), []int{10}
}

func (x *URLPair) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

func (x *URLPair) GetOriginalURL() string {
	if x != nil {
		return x.OriginalURL
	}
	return ""
}

type OwnedURLsOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*URLPair `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *OwnedURLsOut) Reset() {
	*x = OwnedURLsOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverPostFunc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnedURLsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedURLsOut) ProtoMessage() {}

func (x *OwnedURLsOut) ProtoReflect() protoreflect.Message {
	mi := &file_serverPostFunc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedURLsOut.ProtoReflect.Descriptor instead.
func (*OwnedURLsOut) Descriptor() ([]byte, []int) {
	return file_serverPostFunc_proto_rawDescGZIP(), []int{11}
}

func (x *OwnedURLsOut) GetData() []*URLPair {
	if x != nil {
		return x.Data
	}
	return nil
}

type Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URLsCount  int64 `protobuf:"varint,1,opt,name=URLsCount,proto3" json:"URLsCount,omitempty"`
	UsersCount int64 `protobuf:"varint,2,opt,name=UsersCount,proto3" json:"UsersCount,omitempty"`
}

func (x *Stats) Reset() {
	*x = Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverPostFunc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_serverPostFunc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_serverPostFunc_proto_rawDescGZIP(), []int{12}
}

func (x *Stats) GetURLsCount() int64 {
	if x != nil {
		return x.URLsCount
	}
	return 0
}

func (x *Stats) GetUsersCount() int64 {
	if x != nil {
		return x.UsersCount
	}
	return 0
}

var File_serverPostFunc_proto protoreflect.FileDescriptor

var file_serverPostFunc_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x46, 0x75, 0x6e, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x27, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x49, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x55, 0x52, 0x4c, 0x22, 0x2a, 0x0a, 0x0a,
	0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x4f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x55, 0x52, 0x4c, 0x22, 0x26, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x55,
	0x52, 0x4c, 0x49, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x55, 0x52, 0x4c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x55, 0x52, 0x4c,
	0x22, 0x29, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x4f, 0x75, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x55, 0x52, 0x4c, 0x22, 0x59, 0x0a, 0x15, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x49, 0x6e, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x6f, 0x72,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x55, 0x52, 0x4c, 0x22, 0x4f, 0x0a, 0x0e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x49, 0x6e, 0x12, 0x3d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x49, 0x6e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5c, 0x0a, 0x16, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4f, 0x75, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x55, 0x52, 0x4c, 0x22, 0x51, 0x0a, 0x0f, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4f, 0x75, 0x74, 0x12, 0x3e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4f, 0x75, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2b, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x52, 0x4c, 0x49, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x55, 0x52, 0x4c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x55, 0x52, 0x4c, 0x73, 0x22, 0x47, 0x0a, 0x07, 0x55, 0x52, 0x4c, 0x50, 0x61, 0x69, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x20, 0x0a, 0x0b,
	0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x52, 0x4c, 0x22, 0x3f,
	0x0a, 0x0c, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x2f,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70,
	0x62, 0x2e, 0x55, 0x52, 0x4c, 0x50, 0x61, 0x69, 0x72, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x45, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x52, 0x4c, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x55, 0x52, 0x4c,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x73, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xa7, 0x04, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x12, 0x4d, 0x0a, 0x0a, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x50, 0x49, 0x55,
	0x52, 0x4c, 0x12, 0x1d, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x49,
	0x6e, 0x1a, 0x1e, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x4f, 0x75,
	0x74, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x1c, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x49, 0x6e, 0x1a, 0x1d, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0a,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x1f, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x49, 0x6e, 0x1a, 0x19, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0c, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x12, 0x22, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x49, 0x6e, 0x1a, 0x23, 0x2e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70,
	0x62, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4f, 0x75,
	0x74, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x12, 0x19, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x19, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x20, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x77,
	0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x73, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x22, 0x00,
	0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serverPostFunc_proto_rawDescOnce sync.Once
	file_serverPostFunc_proto_rawDescData = file_serverPostFunc_proto_rawDesc
)

func file_serverPostFunc_proto_rawDescGZIP() []byte {
	file_serverPostFunc_proto_rawDescOnce.Do(func() {
		file_serverPostFunc_proto_rawDescData = protoimpl.X.CompressGZIP(file_serverPostFunc_proto_rawDescData)
	})
	return file_serverPostFunc_proto_rawDescData
}

var file_serverPostFunc_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_serverPostFunc_proto_goTypes = []interface{}{
	(*Empty)(nil),                  // 0: internal.server.pb.Empty
	(*PostURLIn)(nil),              // 1: internal.server.pb.PostURLIn
	(*PostURLOut)(nil),             // 2: internal.server.pb.PostURLOut
	(*GetURLIn)(nil),               // 3: internal.server.pb.GetURLIn
	(*GetURLOut)(nil),              // 4: internal.server.pb.GetURLOut
	(*BatchShortenInElement)(nil),  // 5: internal.server.pb.BatchShortenInElement
	(*BatchShortenIn)(nil),         // 6: internal.server.pb.BatchShortenIn
	(*BatchShortenOutElement)(nil), // 7: internal.server.pb.BatchShortenOutElement
	(*BatchShortenOut)(nil),        // 8: internal.server.pb.BatchShortenOut
	(*DeleteURLIn)(nil),            // 9: internal.server.pb.DeleteURLIn
	(*URLPair)(nil),                // 10: internal.server.pb.URLPair
	(*OwnedURLsOut)(nil),           // 11: internal.server.pb.OwnedURLsOut
	(*Stats)(nil),                  // 12: internal.server.pb.Stats
}
var file_serverPostFunc_proto_depIdxs = []int32{
	5,  // 0: internal.server.pb.BatchShortenIn.data:type_name -> internal.server.pb.BatchShortenInElement
	7,  // 1: internal.server.pb.BatchShortenOut.data:type_name -> internal.server.pb.BatchShortenOutElement
	10, // 2: internal.server.pb.OwnedURLsOut.Data:type_name -> internal.server.pb.URLPair
	1,  // 3: internal.server.pb.Shortener.PostAPIURL:input_type -> internal.server.pb.PostURLIn
	3,  // 4: internal.server.pb.Shortener.GetURL:input_type -> internal.server.pb.GetURLIn
	9,  // 5: internal.server.pb.Shortener.DeleteURLs:input_type -> internal.server.pb.DeleteURLIn
	6,  // 6: internal.server.pb.Shortener.BatchShorten:input_type -> internal.server.pb.BatchShortenIn
	0,  // 7: internal.server.pb.Shortener.PingDatabase:input_type -> internal.server.pb.Empty
	0,  // 8: internal.server.pb.Shortener.GetAllOwnedURL:input_type -> internal.server.pb.Empty
	0,  // 9: internal.server.pb.Shortener.GetStats:input_type -> internal.server.pb.Empty
	2,  // 10: internal.server.pb.Shortener.PostAPIURL:output_type -> internal.server.pb.PostURLOut
	4,  // 11: internal.server.pb.Shortener.GetURL:output_type -> internal.server.pb.GetURLOut
	0,  // 12: internal.server.pb.Shortener.DeleteURLs:output_type -> internal.server.pb.Empty
	8,  // 13: internal.server.pb.Shortener.BatchShorten:output_type -> internal.server.pb.BatchShortenOut
	0,  // 14: internal.server.pb.Shortener.PingDatabase:output_type -> internal.server.pb.Empty
	11, // 15: internal.server.pb.Shortener.GetAllOwnedURL:output_type -> internal.server.pb.OwnedURLsOut
	12, // 16: internal.server.pb.Shortener.GetStats:output_type -> internal.server.pb.Stats
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_serverPostFunc_proto_init() }
func file_serverPostFunc_proto_init() {
	if File_serverPostFunc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serverPostFunc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverPostFunc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostURLIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverPostFunc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostURLOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverPostFunc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverPostFunc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverPostFunc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchShortenInElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverPostFunc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchShortenIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverPostFunc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchShortenOutElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverPostFunc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchShortenOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverPostFunc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteURLIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverPostFunc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverPostFunc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OwnedURLsOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverPostFunc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serverPostFunc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serverPostFunc_proto_goTypes,
		DependencyIndexes: file_serverPostFunc_proto_depIdxs,
		MessageInfos:      file_serverPostFunc_proto_msgTypes,
	}.Build()
	File_serverPostFunc_proto = out.File
	file_serverPostFunc_proto_rawDesc = nil
	file_serverPostFunc_proto_goTypes = nil
	file_serverPostFunc_proto_depIdxs = nil
}
